BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,4
,1
,'CONFIRMACION DEL AJUSTADOR'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'CONFIRMACION DEL AJUSTADOR', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 4 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,4
,2
,'ERROR EN FECHAS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ERROR EN FECHAS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 4 AND  COD_CAUSA = 2
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,4
,3
,'ERROR EN CAUSA DE SINIESTRO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ERROR EN CAUSA DE SINIESTRO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 4 AND  COD_CAUSA = 3
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,4
,4
,'AMPLIACION DE DATOS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'AMPLIACION DE DATOS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 4 AND  COD_CAUSA = 4
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,4
,5
,'CORRECCION DE R.F.C.'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'CORRECCION DE R.F.C.', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 4 AND  COD_CAUSA = 5
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,4
,6
,'FALTA DE CIRCUNST Y  RELATO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'FALTA DE CIRCUNST Y  RELATO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 4 AND  COD_CAUSA = 6
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,4
,7
,'OTROS ASPECTOS NO ESPECIFICOS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'OTROS ASPECTOS NO ESPECIFICOS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 4 AND  COD_CAUSA = 7
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,1
,'TRAMITACION FINALIZADA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'TRAMITACION FINALIZADA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,2
,'MAPFRE/MAPFR PAGO DESDE EL RC'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'MAPFRE/MAPFR PAGO DESDE EL RC', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 2
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,3
,'RIESGO EQUIVOCADO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'RIESGO EQUIVOCADO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 3
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,4
,'EXPEDIENTE DUPLICADO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'EXPEDIENTE DUPLICADO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 4
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,5
,'EXPEDIENTE MAL REGISTRADO '
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'EXPEDIENTE MAL REGISTRADO ', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 5
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,6
,'ASEGURADO NO RECLAMA DAÑOS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ASEGURADO NO RECLAMA DAÑOS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 6
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,7
,'DAÑO MENOR AL DEDUCIBLE'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'DAÑO MENOR AL DEDUCIBLE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 7
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,8
,'SINIESTRO NO PROCEDENTE'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'SINIESTRO NO PROCEDENTE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 8
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,9
,'SINIESTRO RECHAZADO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'SINIESTRO RECHAZADO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 9
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,10
,'DAÑOS EXCLUIDOS DE COBERTURA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'DAÑOS EXCLUIDOS DE COBERTURA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 10
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,11
,'ASEG NO RESPONDE A N/REQUERIM'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ASEG NO RESPONDE A N/REQUERIM', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 11
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,12
,'PROVEEDOR NO HA APORTADO FACT'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'PROVEEDOR NO HA APORTADO FACT', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 12
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,9
,'REAP POR JUICIO CIVIL O PENAL'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'REAP POR JUICIO CIVIL O PENAL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 9
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,8
,'QUEJA DE CONDUSEF'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'QUEJA DE CONDUSEF', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 8
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,7
,'SOLICITUD PAGOS DEFENSA LEGAL'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'SOLICITUD PAGOS DEFENSA LEGAL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 7
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,6
,'RECUPERACION DE UNIDAD'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'RECUPERACION DE UNIDAD', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 6
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,5
,'RECUPERACION INGRESO A MAPFRE'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'RECUPERACION INGRESO A MAPFRE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 5
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,4
,'PAGO EXGRATIA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'PAGO EXGRATIA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 4
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,3
,'INSERCION DE EXPEDIENTES'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'INSERCION DE EXPEDIENTES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 3
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,2
,'PAGOS PENDIENTES'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'PAGOS PENDIENTES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 2
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,1
,'CANCELACION DE LA LIQUIDACION'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'CANCELACION DE LA LIQUIDACION', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,6
,9999
,'TERMINACION AUTOMATICA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'TERMINACION AUTOMATICA'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'TERMINACION AUTOMATICA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'TERMINACION AUTOMATICA'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 6 AND  COD_CAUSA = 9999
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,15
,9999
,'APERTURA AUTOMATICA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'APERTURA AUTOMATICA'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'APERTURA AUTOMATICA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'APERTURA AUTOMATICA'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 15 AND  COD_CAUSA = 9999
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,1
,'COLISION Y/O VOLCADURA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'COLISION Y/O VOLCADURA'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'COLISION Y/O VOLCADURA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'COLISION Y/O VOLCADURA'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,2
,'ROBO TOTAL'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'ROBO TOTAL'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ROBO TOTAL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'ROBO TOTAL'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 2
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,3
,'ROBO PARCIAL'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'ROBO PARCIAL'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ROBO PARCIAL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'ROBO PARCIAL'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 3
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,4
,'INCENDIO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'INCENDIO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'INCENDIO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'INCENDIO'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 4
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,5
,'ALBOROTOS POPULARES'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'ALBOROTOS POPULARES'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ALBOROTOS POPULARES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'ALBOROTOS POPULARES'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 5
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,6
,'ROTURA DE CRISTALES'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'ROTURA DE CRISTALES'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ROTURA DE CRISTALES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'ROTURA DE CRISTALES'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 6
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,7
,'ESPEJOS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'ESPEJOS'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ESPEJOS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'ESPEJOS'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 7
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,8
,'GARANTIA SOBRE RUEDAS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'GARANTIA SOBRE RUEDAS'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'GARANTIA SOBRE RUEDAS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'GARANTIA SOBRE RUEDAS'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 8
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,9
,'ATROPELLO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'ATROPELLO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ATROPELLO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'ATROPELLO'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 9
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,10
,'FENOMENOS NATURALES'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'FENOMENOS NATURALES'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'FENOMENOS NATURALES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'FENOMENOS NATURALES'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 10
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,1
,11
,'ASISTENCIA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'ASISTENCIA'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ASISTENCIA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'ASISTENCIA'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 1 AND  COD_CAUSA = 11
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,2
,1
,'CONFIRMACION DEL AJUSTADOR'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'CONFIRMACION DEL AJUSTADOR', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 2 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,2
,2
,'ERROR EN FECHAS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ERROR EN FECHAS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 2 AND  COD_CAUSA = 2
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,2
,3
,'ERROR EN CAUSA DE SINIESTRO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ERROR EN CAUSA DE SINIESTRO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 2 AND  COD_CAUSA = 3
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,2
,4
,'AMPLIACION DE DATOS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'AMPLIACION DE DATOS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 2 AND  COD_CAUSA = 4
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,2
,5
,'CORRECCION DE R.F.C.'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'CORRECCION DE R.F.C.', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 2 AND  COD_CAUSA = 5
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,2
,6
,'FALTA DE CIRCUNST Y  RELATO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'FALTA DE CIRCUNST Y  RELATO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 2 AND  COD_CAUSA = 6
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,2
,7
,'OTROS ASPECTOS NO ESPECIFICOS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'OTROS ASPECTOS NO ESPECIFICOS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 2 AND  COD_CAUSA = 7
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,1
,'CANCELACION DE LA LIQUIDACION'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'CANCELACION DE LA LIQUIDACION', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,2
,'PAGOS PENDIENTES'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'PAGOS PENDIENTES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 2
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,3
,'INSERCION DE EXPEDIENTES'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'INSERCION DE EXPEDIENTES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 3
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,4
,'PAGO EXGRATIA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'PAGO EXGRATIA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 4
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,5
,'RECUPERACION INGRESO A MAPFRE'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'RECUPERACION INGRESO A MAPFRE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 5
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,6
,'RECUPERACION DE UNIDAD'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'RECUPERACION DE UNIDAD', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 6
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,7
,'SOLICITUD PAGOS DEFENSA LEGAL'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'SOLICITUD PAGOS DEFENSA LEGAL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 7
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,8
,'QUEJA DE CONDUSEF'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'QUEJA DE CONDUSEF', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 8
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,9
,'REAP POR JUICIO CIVIL O PENAL'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'REAP POR JUICIO CIVIL O PENAL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 9
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,3
,9999
,'REHABILITACION AUTOMATICA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'REHABILITACION AUTOMATICA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 3 AND  COD_CAUSA = 9999
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,1
,'TRAMITACION FINALIZADA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'TRAMITACION FINALIZADA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,2
,'MAPFRE/MAPFR PAGO DESDE EL RC'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'MAPFRE/MAPFR PAGO DESDE EL RC', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 2
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,3
,'RIESGO EQUIVOCADO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'RIESGO EQUIVOCADO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 3
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,4
,'ASEGURADO NO RECLAMA DAÑOS'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ASEGURADO NO RECLAMA DAÑOS', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 4
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,5
,'DAÑO MENOR AL DEDUCIBLE'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'DAÑO MENOR AL DEDUCIBLE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 5
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,6
,'SINIESTRO NO PROCEDENTE'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'SINIESTRO NO PROCEDENTE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 6
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,7
,'SINIESTRO RECHAZADO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'SINIESTRO RECHAZADO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 7
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,8
,'DAÑOS EXCLUIDOS DE COBERTURA'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'DAÑOS EXCLUIDOS DE COBERTURA', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 8
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,9
,'ASEG NO RESPONDE A N/REQUERIM'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'ASEG NO RESPONDE A N/REQUERIM', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 9
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,9
,9999
,'TERMINACION SINIESTRO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'TERMINACION SINIESTRO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'TERMINACION SINIESTRO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'TERMINACION SINIESTRO'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 9 AND  COD_CAUSA = 9999
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,17
,1
,'RECLASIFICACION DEL INVENTARIO'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'RECLASIFICACION DEL INVENTARIO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'RECLASIFICACION DEL INVENTARIO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'RECLASIFICACION DEL INVENTARIO'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 17 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,5
,9999
,'REHABILITACION AUTOMATICA EXP'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'REHABILITACION AUTOMATICA EXP', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = NULL
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 5 AND  COD_CAUSA = 9999
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,18
,1
,'INSPECCION POLICIAL'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'INSPECCION POLICIAL'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'INSPECCION POLICIAL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'INSPECCION POLICIAL'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 18 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,8
,1
,'INSPECCION D.MATERIALES (ASEG)'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'INSPECCION D.MATERIALES (ASEG)'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'INSPECCION D.MATERIALES (ASEG)', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'INSPECCION D.MATERIALES (ASEG)'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 8 AND  COD_CAUSA = 1
;
END;
BEGIN 
INSERT INTO TRON2000.G7000200
(COD_CIA
,TIP_CAUSA
,COD_CAUSA
,NOM_CAUSA
,MCA_INH
,COD_USR
,FEC_ACTU
,MCA_TRAMITABLE
,NOM_CAUSA_CARTA
)
VALUES ( 
1
,8
,2
,'INSPECCION D.MATERIALES (CONT)'
,'N'
,'TRON2000'
,SYSDATE
,'S'
,'INSPECCION D.MATERIALES (CONT)'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000200
 SET  NOM_CAUSA = 'INSPECCION D.MATERIALES (CONT)', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_TRAMITABLE = 'S', NOM_CAUSA_CARTA = 'INSPECCION D.MATERIALES (CONT)'
 WHERE  COD_CIA = 1 AND  TIP_CAUSA = 8 AND  COD_CAUSA = 2
;
END;
END;
/
COMMIT;