REM INSERTING into TRON2000.G1010031
SET DEFINE OFF;
Insert into TRON2000.G1010031 (COD_CAMPO,NUM_ORDEN,COD_VALOR,COD_IDIOMA,NOM_VALOR,COD_RAMO,COD_INSTALACION) values ('TXT_AUX1',8,'GR','ES','HONORARIOS GRUEROS',999,'TRN');
Insert into TRON2000.G1010031 (COD_CAMPO,NUM_ORDEN,COD_VALOR,COD_IDIOMA,NOM_VALOR,COD_RAMO,COD_INSTALACION) values ('TXT_AUX1',9,'GQ','ES','GRUEROS MORALES',999,'TRN');
Insert into TRON2000.G1010031 (COD_CAMPO,NUM_ORDEN,COD_VALOR,COD_IDIOMA,NOM_VALOR,COD_RAMO,COD_INSTALACION) values ('TXT_AUX1',4,'DO','ES','HONORARIOS INT.REPUBLICA',999,'TRN');
Insert into TRON2000.G1010031 (COD_CAMPO,NUM_ORDEN,COD_VALOR,COD_IDIOMA,NOM_VALOR,COD_RAMO,COD_INSTALACION) values ('TXT_AUX1',5,'ND','ES','HONORARIOS FRONTERIZA',999,'TRN');
Insert into TRON2000.G1010031 (COD_CAMPO,NUM_ORDEN,COD_VALOR,COD_IDIOMA,NOM_VALOR,COD_RAMO,COD_INSTALACION) values ('TXT_AUX1',6,'RM','ES','RETENCION PERSONA MORAL',999,'TRN');
Insert into TRON2000.G1010031 (COD_CAMPO,NUM_ORDEN,COD_VALOR,COD_IDIOMA,NOM_VALOR,COD_RAMO,COD_INSTALACION) values ('TXT_AUX1',7,'IF','ES','IVA FRONTERIZO 8%',999,'TRN');
commit;
