BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'9999'
,'GENERAL AL PLAN'
,'NIVELGEN'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'GENERAL AL PLAN', NOM_COR_NIVEL = 'NIVELGEN', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '9999'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'400'
,'CAPTURA Y APERTURA'
,'CAPYAPER'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'CAPTURA Y APERTURA', NOM_COR_NIVEL = 'CAPYAPER', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'401'
,'DISTRIBUCION DE SINIESTROS'
,'DISTSINI'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'DISTRIBUCION DE SINIESTROS', NOM_COR_NIVEL = 'DISTSINI', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'402'
,'TRAMITE GENERAL'
,'TRAMGEN'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE GENERAL', NOM_COR_NIVEL = 'TRAMGEN', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'403'
,'TRAMITE RECLAMACION DAÃ`OS/REC'
,'TRAMRECDAN'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE RECLAMACION DAÃ`OS/REC', NOM_COR_NIVEL = 'TRAMRECDAN', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '403'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'404'
,'TRAMITE DAÃ`OS (RC)'
,'TAMDAN'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE DAÃ`OS (RC)', NOM_COR_NIVEL = 'TAMDAN', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '404'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'405'
,'TRAMITE LESIONADOS (RC)'
,'TRAMLES'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE LESIONADOS (RC)', NOM_COR_NIVEL = 'TRAMLES', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '405'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'406'
,'TRAMITE FALLECIDOS (RC)'
,'TRAMFALL'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE FALLECIDOS (RC)', NOM_COR_NIVEL = 'TRAMFALL', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '406'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'407'
,'TRAMITE GESTION DE RESTOS/REC'
,'TRAMREST'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE GESTION DE RESTOS/REC', NOM_COR_NIVEL = 'TRAMREST', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '407'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'408'
,'TRAMITE PERDIDA TOTAL/ROBO'
,'TRAMPER'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE PERDIDA TOTAL/ROBO', NOM_COR_NIVEL = 'TRAMPER', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '408'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'409'
,'TRAMITE EXTRANJEROS'
,'TRAMEXT'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE EXTRANJEROS', NOM_COR_NIVEL = 'TRAMEXT', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '409'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'410'
,'TRAMITE JUDICIAL'
,'TRAMJUD'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE JUDICIAL', NOM_COR_NIVEL = 'TRAMJUD', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '410'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'411'
,'MOVIMIENTOS ECONOMICOS'
,'MOVECO'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'MOVIMIENTOS ECONOMICOS', NOM_COR_NIVEL = 'MOVECO', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'412'
,'GESTION DEL FRAUDE'
,'GESTFRAU'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'GESTION DEL FRAUDE', NOM_COR_NIVEL = 'GESTFRAU', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '412'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'413'
,'GESTION DE CALIDAD'
,'GESCALID'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'GESTION DE CALIDAD', NOM_COR_NIVEL = 'GESCALID', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'414'
,'CIERRE'
,'CIERRE'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'CIERRE', NOM_COR_NIVEL = 'CIERRE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'1'
,'CAPTURA Y APERTURA'
,'CAP.APER.'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'CAPTURA Y APERTURA', NOM_COR_NIVEL = 'CAP.APER.', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '1'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'2'
,'TRAMITE GENERAL'
,'TRAM.GEN.'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'TRAMITE GENERAL', NOM_COR_NIVEL = 'TRAM.GEN.', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '2'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'3'
,'MOVIMIENTOS ECONOMICOS'
,'MOV.ECO.'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'MOVIMIENTOS ECONOMICOS', NOM_COR_NIVEL = 'MOV.ECO.', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '3'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4'
,'GESTION CALIDAD'
,'GES.CALID.'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'GESTION CALIDAD', NOM_COR_NIVEL = 'GES.CALID.', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '4'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500010
(COD_CIA
,COD_NIVEL
,NOM_NIVEL
,NOM_COR_NIVEL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'5'
,'CIERRE'
,'CIERRE'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500010
 SET  NOM_NIVEL = 'CIERRE', NOM_COR_NIVEL = 'CIERRE', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_NIVEL = '5'
;
END;
END;
/
COMMIT;