BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'999'
,'EXPEDIENTE GENERICO'
,'N'
,'N'
,NULL
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'GE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'EXPEDIENTE GENERICO', MCA_SINI = 'N', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'GE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = '999'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RAA'
,'RECUPERACION ANTE ASEGURADO'
,'S'
,'S'
,'R'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RECUPERACION ANTE ASEGURADO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'R', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RAA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'DMP'
,'DAÑOS MATERIALES PARCIALES'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'DP'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'DAÑOS MATERIALES PARCIALES', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'DP'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'DMP'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'DED'
,'DEDUCIBLE'
,'S'
,'S'
,'R'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'DEDUCIBLE', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'R', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'PTD'
,'PERDIDA TOTAL POR DAÑOS'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'DP'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'PERDIDA TOTAL POR DAÑOS', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP 
 = 'DP'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'PTD'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'DPC'
,'DAÑOS CRISTALES'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'DP'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'DAÑOS CRISTALES', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 'DP'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'DPC'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RTA'
,'ROBO TOTAL'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'DP'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'ROBO TOTAL', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 'DP'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RTA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RPA'
,'ROBO PARCIAL'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'AC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'ROBO PARCIAL', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 'AC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RPA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RCB'
,'RESPONSABILIDAD CIVIL BIENES'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'RC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RESPONSABILIDAD CIVIL BIENES', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RCB'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RCI'
,'RESPONSABILIDAD CIVIL INMUEBLE'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'RC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RESPONSABILIDAD CIVIL INMUEBLE', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RCI'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RCP'
,'RESPONSABILIDAD CIVIL PERSONAS'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'RC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RESPONSABILIDAD CIVIL PERSONAS', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RCP'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RCV'
,'RESPONSABILIDAD CIVIL VIAJERO'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'RC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RESPONSABILIDAD CIVIL VIAJERO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RCV'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RCU'
,'RESPONSABILIDAD CIVIL USA'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'RC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RESPONSABILIDAD CIVIL USA', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RCU'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RDE'
,'RESPONSABILIDAD DAÑO ECOLOGICO'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'RC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RESPONSABILIDAD DAÑO ECOLOGICO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RDE'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'LEO'
,'LESIONES OCUPANTES'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'LE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'LESIONES OCUPANTES', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'LE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'LEO'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'ACC'
,'ACCIDENTES AL CONDUCTOR'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'LE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'ACCIDENTES AL CONDUCTOR', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP 
 = 'LE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'ACC'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'DJA'
,'DEFENSA JURIDICA ASEGURADO'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'GE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'DEFENSA JURIDICA ASEGURADO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'GE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'DJA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'GAP'
,'AUTO GAP GTI'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'DP'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'AUTO GAP GTI', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 'DP'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'GAP'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'GSR'
,'GARANTIA SOBRE RUEDAS'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'DP'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'GARANTIA SOBRE RUEDAS', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'DP'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'GSR'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'DAS'
,'DEVOLUCION AUTO SUSTITUTO'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'GE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'DEVOLUCION AUTO SUSTITUTO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'GE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'DAS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'ASI'
,'ASISTENCIA VIAL'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'GE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'ASISTENCIA VIAL', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 'GE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'ASI'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'SDT'
,'SALVAMENTO POR DAÑOS TERCERO'
,'S'
,'S'
,'S'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'SALVAMENTO POR DAÑOS TERCERO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'S', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'SDT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'SDA'
,'SALVAMENTO POR DAÑOS ASEGURADO'
,'S'
,'S'
,'S'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'SALVAMENTO POR DAÑOS ASEGURADO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'S', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'SDA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RMT'
,'RECUPERACION MATERIAL TRAD'
,'S'
,'S'
,'R'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RECUPERACION MATERIAL TRAD', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'R', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RMS'
,'RECUPERACION MATERIAL SIPAC'
,'S'
,'S'
,'R'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RECUPERACION MATERIAL SIPAC', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'R', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RLT'
,'RECUPERACION LESIONES TRAD'
,'S'
,'S'
,'R'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RECUPERACION LESIONES TRAD', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'R', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RLS'
,'RECUPERACION LESIONES SIPAC'
,'S'
,'S'
,'R'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RECUPERACION LESIONES SIPAC', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'R', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RLS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'RM'
,'RECUPERACION MONETARIA'
,'S'
,'S'
,'R'
,'N'
,'N'
,'TRON2000'
,SYSDATE
,'RE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'RECUPERACION MONETARIA', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'S', TIP_EXP_RECOBRO = 'R', MCA_POSITIVO = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'RE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'PMT'
,'PAGOS MATERIAL TRADICIONAL'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'CO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'PAGOS MATERIAL TRADICIONAL', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'CO'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'PMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'PMS'
,'PAGOS MATERIAL SIPAC'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'CO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'PAGOS MATERIAL SIPAC', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'CO'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'PMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'PLT'
,'PAGOS LESIONES TRADICIONAL'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'CO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'PAGOS LESIONES TRADICIONAL', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 TIP_AGRUP_TIP_EXP = 'CO'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'PLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'PLS'
,'PAGOS LESIONES SIPAC'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'CO'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'PAGOS LESIONES SIPAC', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'CO'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'PLS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'DIV'
,'DIVIDENDO /BONIFICACION'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'GE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'DIVIDENDO /BONIFICACION', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP 
 = 'GE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'DIV'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'DDP'
,'DEVOLUCION DE PRIMA'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'GE'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'DEVOLUCION DE PRIMA', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'GE'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'DDP'
;
END;
BEGIN 
INSERT INTO TRON2000.G7000090
(COD_CIA
,TIP_EXP
,NOM_EXP
,MCA_SINI
,MCA_EXP_RECOBRO
,TIP_EXP_RECOBRO
,MCA_POSITIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,TIP_AGRUP_TIP_EXP
)
VALUES ( 
1
,'PTT'
,'PERDIDA TOTAL TERCERO'
,'S'
,'N'
,NULL
,'S'
,'N'
,'TRON2000'
,SYSDATE
,'RC'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7000090
 SET  NOM_EXP = 'PERDIDA TOTAL TERCERO', MCA_SINI = 'S', MCA_EXP_RECOBRO = 'N', TIP_EXP_RECOBRO = NULL, MCA_POSITIVO = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, TIP_AGRUP_TIP_EXP = 
 'RC'
 WHERE  COD_CIA = 1 AND  TIP_EXP = 'PTT'
;
END;
END;
/
COMMIT;