BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'OM1'
,99
,'230302011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230302011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'OM1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'PF1'
,1
,'530937011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'PF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'PM1'
,1
,'530937011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'PM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'RM1'
,1
,'530937031'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937031', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'RM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'RM2'
,1
,'530937031'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937031', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'RM2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'RM3'
,1
,'530937131'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937131', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'RM3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'RM4'
,1
,'530937151'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937151', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'RM4' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'RM5'
,1
,'530937151'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937151', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'RM5' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'SF1'
,99
,'230201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'SF1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'SF2'
,99
,'162201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '162201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'SF2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'SM1'
,99
,'230202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'SM1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'SM2'
,99
,'162202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '162202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'SM2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'TF1'
,99
,'162201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '162201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'TF1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'TF2'
,99
,'230201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'TF2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'TM1'
,99
,'162202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '162202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'TM1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'TM2'
,99
,'230202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'TM2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'UF1'
,1
,'530937091'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937091', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'UF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'UM1'
,1
,'530937101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'UM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'VF1'
,1
,'230201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'VF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'VM1'
,1
,'230202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'VM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y12'
,1
,'541125281'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125281', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y12' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y12'
,2
,'541125281'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125281', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y12' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y13'
,1
,'541125261'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125261', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y13' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y13'
,2
,'541125261'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125261', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y13' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'A'
,'ac'
,1
,'260512151'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'A', COD_CTA = '260512151', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'ac' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'AP1'
,2
,'230600021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230600021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'AP1' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'AP2'
,2
,'230700011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230700011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'AP2' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'CAM'
,1
,'662102011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '662102011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CAM' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'APC'
,99
,'240700011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '240700011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'APC' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'AP3'
,99
,'240700031'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '240700031', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'AP3' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'A'
,'Dn'
,2
,'170101011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'A', COD_CTA = '170101011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Dn' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'ID2'
,1
,'540101071'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '540101071', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'ID2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'ID2'
,2
,'540101071'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '540101071', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'ID2' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'A'
,'DN'
,99
,'170103241'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'A', COD_CTA = '170103241', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DN' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IR2'
,1
,'642200011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '642200011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IR2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IR2'
,2
,'642200011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '642200011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IR2' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IR3'
,2
,'642200011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '642200011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IR3' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IR4'
,2
,'642200011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '642200011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IR4' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IR3'
,1
,'642200011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '642200011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IR3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IR4'
,1
,'642200011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '642200011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IR4' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IS2'
,1
,'641300031'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '641300031', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IS2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'IS2'
,2
,'641300031'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '641300031', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IS2' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'ANT'
,99
,'213302011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '213302011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'ANT' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H03'
,2
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H03' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H03'
,1
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H03' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H05'
,2
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H05' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H05'
,1
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H05' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H06'
,1
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H06' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H06'
,2
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H06' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H09'
,1
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H09' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H09'
,2
,'541125081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541125081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H09' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I03'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I03' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I03'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I03' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I04'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I04' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I04'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I04' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I05'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I05' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I05'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I05' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I07'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I07' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I07'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I07' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I08'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I08' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'I08'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'I08' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y04'
,1
,'541126091'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541126091', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y04' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y04'
,2
,'541126091'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541126091', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y04' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H10'
,1
,'541145051'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541145051', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H10' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H10'
,2
,'541145051'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541145051', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H10' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y10'
,1
,'541116021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541116021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y10' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y10'
,2
,'541116021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541116021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y10' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y11'
,1
,'541116021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541116021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y11' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y11'
,2
,'541116021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541116021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y11' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H11'
,1
,'541157011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541157011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H11' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'H11'
,2
,'541157011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541157011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'H11' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y08'
,2
,'541145051'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541145051', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y08' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y08'
,1
,'541145051'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541145051', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y08' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y14'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y14' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y14'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y14' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y16'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y16' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y16'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y16' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y17'
,1
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y17' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y17'
,2
,'540101101'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '540101101', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y17' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y26'
,2
,'541145051'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541145051', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y26' AND  COD_MON = 2
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'Y26'
,1
,'541145051'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '541145051', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'Y26' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'DN1'
,99
,'170103241'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '170103241', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DN1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CA6'
,99
,'170103411'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '170103411', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CA6' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'A'
,'AF1'
,99
,'530306011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'A', COD_CTA = '530306011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'AF1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'A'
,'AM1'
,99
,'530506011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'A', COD_CTA = '530506011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'AM1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BF1'
,1
,'530404011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530404011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BF2'
,1
,'530404081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530404081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BF2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BF3'
,1
,'530404081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530404081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BF3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BF4'
,99
,'530404091'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530404091', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BF4' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BM1'
,1
,'530604011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530604011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BM2'
,1
,'530604081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530604081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BM2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BM3'
,1
,'530604081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530604081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BM3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'BM4'
,99
,'530604091'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530604091', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'BM4' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CF1'
,99
,'662102011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '662102011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CF1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CF2'
,99
,'662102011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '662102011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CF2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CF3'
,1
,'213301011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '213301011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CF3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CF4'
,1
,'230201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '230201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CF4' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CF5'
,1
,'213301011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '213301011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CF5' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CM1'
,99
,'662102011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '662102011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CM1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CM2'
,99
,'662102011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '662102011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CM2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CM3'
,1
,'213301011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '213301011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CM3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CM4'
,1
,'230202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '230202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CM4' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'CM5'
,1
,'213301011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '213301011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'CM5' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'DF1'
,1
,'530404041'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530404041', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'DF2'
,99
,'530404021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530404021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DF2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'DF3'
,1
,'650600501'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '650600501', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DF3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'DM1'
,1
,'530604031'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530604031', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'DM2'
,99
,'530604021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530604021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DM2' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'DM3'
,1
,'650600501'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '650600501', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'DM3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'FF1'
,1
,'230201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '230201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'FF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'FM2'
,1
,'230202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '230202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'FM2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'HF1'
,1
,'530937021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'HF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'HM1'
,1
,'530937021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530937021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'HM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IF1'
,1
,'530404081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530404081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IF2'
,1
,'260502011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260502011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IF2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IF3'
,1
,'260512151'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260512151', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IF3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IF4'
,1
,'163306011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '163306011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IF4' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IF5'
,1
,'260509151'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260509151', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IF5' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IF6'
,1
,'260513021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260513021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IF6' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IM1'
,1
,'530604081'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '530604081', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IM2'
,1
,'260502011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260502011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IM2' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IM3'
,1
,'260512151'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260512151', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IM3' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IM4'
,1
,'163306011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '163306011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IM4' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IM5'
,1
,'260509151'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260509151', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IM5' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'IM6'
,1
,'260513021'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '260513021', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'IM6' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'LF1'
,1
,'230201011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '230201011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'LF1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'C'
,'LM1'
,1
,'230202011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'C', COD_CTA = '230202011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'LM1' AND  COD_MON = 1
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'NF1'
,99
,'650600011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '650600011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'NF1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'NM1'
,99
,'650600011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '650600011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'NM1' AND  COD_MON = 99
;
END;
BEGIN 
INSERT INTO TRON2000.A5021100
(COD_CIA
,TIP_COB_PAG
,COD_CTO_COB_PAG
,COD_MON
,COD_CTA
,COD_CTA_PRV
,COD_PGM_PRE
,COD_PGM_POS
,COD_USR
,FEC_ACTU
,COD_CTA_REAL
)
VALUES ( 
1
,'P'
,'OF1'
,99
,'230301011'
,NULL
,NULL
,NULL
,'TRON2000'
,SYSDATE
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021100
 SET  TIP_COB_PAG = 'P', COD_CTA = '230301011', COD_CTA_PRV = NULL, COD_PGM_PRE = NULL, COD_PGM_POS = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, COD_CTA_REAL = NULL
 WHERE  COD_CIA = 1 AND  COD_CTO_COB_PAG = 'OF1' AND  COD_MON = 99
;
END;
END;
/
COMMIT;