BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'1'
,'1'
,1
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '1' AND  COD_NIVEL = '1'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'1'
,'2'
,2
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '1' AND  COD_NIVEL = '2'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'1'
,'3'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '1' AND  COD_NIVEL = '3'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'1'
,'4'
,4
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '1' AND  COD_NIVEL = '4'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'1'
,'5'
,5
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '1' AND  COD_NIVEL = '5'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'402'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'410'
,4
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '410'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'411'
,5
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'412'
,6
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 6, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '412'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'413'
,7
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ASI'
,'414'
,8
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 8, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ASI' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'402'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'408'
,4
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '408'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'409'
,5
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '409'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'410'
,6
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 6, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '410'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'411'
,7
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'412'
,8
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 8, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '412'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'413'
,9
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 9, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DAN'
,'414'
,10
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 10, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DAN' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DED'
,'400'
,1
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DED' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DED'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DED' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DED'
,'402'
,3
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DED' AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DED'
,'403'
,4
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DED' AND  COD_NIVEL = '403'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DED'
,'411'
,5
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DED' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DED'
,'413'
,7
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DED' AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DED'
,'414'
,8
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 8, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DED' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DIV'
,'400'
,1
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DIV' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DIV'
,'402'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DIV' AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DIV'
,'411'
,3
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DIV' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DIV'
,'414'
,4
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DIV' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DPJ'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DPJ' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DPJ'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DPJ' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DPJ'
,'402'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DPJ' AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DPJ'
,'410'
,4
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DPJ' AND  COD_NIVEL = '410'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DPJ'
,'411'
,5
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DPJ' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DPJ'
,'413'
,7
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DPJ' AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4DPJ'
,'414'
,8
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 8, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4DPJ' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'402'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'405'
,4
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '405'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'406'
,5
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '406'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'410'
,6
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 6, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '410'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'411'
,7
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'412'
,8
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 8, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '412'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'413'
,9
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 9, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4LYM'
,'414'
,10
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 10, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4LYM' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PDM'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PDM' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PDM'
,'404'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PDM' AND  COD_NIVEL = '404'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PDM'
,'411'
,4
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PDM' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PDM'
,'414'
,5
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PDM' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PL'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PL' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PL'
,'405'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PL' AND  COD_NIVEL = '405'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PL'
,'406'
,4
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PL' AND  COD_NIVEL = '406'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PL'
,'410'
,5
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PL' AND  COD_NIVEL = '410'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PL'
,'411'
,6
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 6, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PL' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4PL'
,'414'
,7
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4PL' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4REC'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4REC' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4REC'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4REC' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4REC'
,'403'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4REC' AND  COD_NIVEL = '403'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4REC'
,'411'
,4
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4REC' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4REC'
,'412'
,5
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4REC' AND  COD_NIVEL = '412'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4REC'
,'414'
,6
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 6, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4REC' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4SAL'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4SAL' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4SAL'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4SAL' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4SAL'
,'407'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4SAL' AND  COD_NIVEL = '407'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4SAL'
,'408'
,4
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4SAL' AND  COD_NIVEL = '408'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4SAL'
,'411'
,5
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4SAL' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4SAL'
,'413'
,6
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 6, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4SAL' AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4SAL'
,'414'
,7
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4SAL' AND  COD_NIVEL = '414'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'400'
,1
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 1, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '400'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'401'
,2
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 2, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '401'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'408'
,3
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 3, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '408'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'410'
,4
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 4, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '410'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'411'
,5
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 5, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '411'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'412'
,6
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 6, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '412'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'413'
,7
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 7, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '413'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'402'
,8
,'N'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 8, MCA_NIVEL_INICIAL = 'N', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '402'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500060
(COD_CIA
,COD_PLAN
,COD_NIVEL
,NUM_SECU_NIVEL
,MCA_NIVEL_INICIAL
,MCA_INH
,COD_USR
,FEC_ACTU
)
VALUES ( 
1
,'4ROB'
,'414'
,9
,'S'
,'N'
,'TRON2000'
,SYSDATE
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500060
 SET  NUM_SECU_NIVEL = 9, MCA_NIVEL_INICIAL = 'S', MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE
 WHERE  COD_CIA = 1 AND  COD_PLAN = '4ROB' AND  COD_NIVEL = '414'
;
END;
END;
/
COMMIT;