BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'DMP'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'DMP'
,'RMT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'DMP'
,'RMS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'DMP'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'PTD'
,'SDA'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'SDA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'PTD'
,'RMT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'PTD'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'PTD'
,'RMS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'DPC'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'DPC' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'RTA'
,'SDA'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'RTA' AND  TIP_EXP_REC = 'SDA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'RPA'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'RPA' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'PTT'
,'SDT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'PTT' AND  TIP_EXP_REC = 'SDT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'LEO'
,'RLS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RLS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'LEO'
,'RLT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'LEO'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'ACC'
,'RLT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'ACC' AND  TIP_EXP_REC = 'RLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,410
,'ACC'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 410 AND  TIP_EXP = 'ACC' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'DMP'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'DMP'
,'RMT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'DMP'
,'RMS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'DMP'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'PTD'
,'SDA'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'SDA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'PTD'
,'RMT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'PTD'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'PTD'
,'RMS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'DPC'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'DPC' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'RTA'
,'SDA'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'RTA' AND  TIP_EXP_REC = 'SDA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'RPA'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'RPA' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'PTT'
,'SDT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'PTT' AND  TIP_EXP_REC = 'SDT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'LEO'
,'RLS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RLS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'LEO'
,'RLT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'LEO'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'ACC'
,'RLT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'ACC' AND  TIP_EXP_REC = 'RLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,411
,'ACC'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 411 AND  TIP_EXP = 'ACC' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'DMP'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'DMP'
,'RMT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'DMP'
,'RMS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'DMP'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'DMP' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'PTD'
,'SDA'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'SDA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'PTD'
,'RMT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RMT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'PTD'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'PTD'
,'RMS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'PTD' AND  TIP_EXP_REC = 'RMS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'DPC'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'DPC' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'RTA'
,'SDA'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'RTA' AND  TIP_EXP_REC = 'SDA'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'RPA'
,'DED'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'RPA' AND  TIP_EXP_REC = 'DED'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'PTT'
,'SDT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'PTT' AND  TIP_EXP_REC = 'SDT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'LEO'
,'RLS'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RLS'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'LEO'
,'RLT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'LEO'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'LEO' AND  TIP_EXP_REC = 'RM'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'ACC'
,'RLT'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'ACC' AND  TIP_EXP_REC = 'RLT'
;
END;
BEGIN 
INSERT INTO TRON2000.G7007030
(COD_CIA
,COD_RAMO
,TIP_EXP
,TIP_EXP_REC
,COD_USR
,FEC_ACTU
,MCA_APER_AUT
,NOM_PRG_APER_AUT
)
VALUES ( 
1
,450
,'ACC'
,'RM'
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7007030
 SET  COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, MCA_APER_AUT = 'N', NOM_PRG_APER_AUT = NULL
 WHERE  COD_CIA = 1 AND  COD_RAMO = 450 AND  TIP_EXP = 'ACC' AND  TIP_EXP_REC = 'RM'
;
END;
END;
/
COMMIT;