BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'C0'
,'IVA COBRADO AL 0% PRIMAS'
,'COBR 0%'
,'R'
,'I'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'IVA COBRADO AL 0% PRIMAS', NOM_COR_IMPTO = 'COBR 0%', TIP_IVA = 'R', TIP_IMPTO = 'I', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'C0'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'C16'
,'IVA COBRADO AL 16% PRIMAS'
,'COBR 16%'
,'R'
,'I'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'IVA COBRADO AL 16% PRIMAS', NOM_COR_IMPTO = 'COBR 16%', TIP_IVA = 'R', TIP_IMPTO = 'I', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU 
 = SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'C16'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'C17'
,'IVA COBRADO AL 16% SALVAM'
,'SALVAM 16%'
,'R'
,'I'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'IVA COBRADO AL 16% SALVAM', NOM_COR_IMPTO = 'SALVAM 16%', TIP_IVA = 'R', TIP_IMPTO = 'I', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', 
 FEC_ACTU = SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'C17'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'C18'
,'IVA COBRADO AL 16% OTROS'
,'OTROS 16%'
,'R'
,'I'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'IVA COBRADO AL 16% OTROS', NOM_COR_IMPTO = 'OTROS 16%', TIP_IVA = 'R', TIP_IMPTO = 'I', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU 
 = SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'C18'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'A8'
,'IVA X ACREDITAR AL 8%'
,'ACRED ZF8%'
,'S'
,'I'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'IVA X ACREDITAR AL 8%', NOM_COR_IMPTO = 'ACRED ZF8%', TIP_IVA = 'S', TIP_IMPTO = 'I', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'A8'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'A16'
,'IVA X ACREDITAR AL 16%'
,'ACRED 16%'
,'S'
,'I'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'IVA X ACREDITAR AL 16%', NOM_COR_IMPTO = 'ACRED 16%', TIP_IVA = 'S', TIP_IMPTO = 'I', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'A16'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'ISR'
,'ISR 10%'
,'RET ISR10%'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'ISR 10%', NOM_COR_IMPTO = 'RET ISR10%', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'ISR'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'R20'
,'ISR 20% '
,'RET ISR20%'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'ISR 20% ', NOM_COR_IMPTO = 'RET ISR20%', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'R20'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'R25'
,'ISR 25%'
,'RET ISR25%'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'ISR 25%', NOM_COR_IMPTO = 'RET ISR25%', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'R25'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'RE7'
,'RETENCION VR'
,'RE7'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'RETENCION VR', NOM_COR_IMPTO = 'RE7', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'RE7'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'RE8'
,'RETENCION VR'
,'RE8'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'RETENCION VR', NOM_COR_IMPTO = 'RE8', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'RE8'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'RUL'
,'RETENCION UNIT LINKED'
,'RUL'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'RETENCION UNIT LINKED', NOM_COR_IMPTO = 'RUL', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'RUL'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'RV1'
,'LISR BENEFICIARIO VIDA'
,'RV1'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'LISR BENEFICIARIO VIDA', NOM_COR_IMPTO = 'RV1', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'RV1'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'RV2'
,'LISR BENEFICIARIO VIDA'
,'RV2'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'LISR BENEFICIARIO VIDA', NOM_COR_IMPTO = 'RV2', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'RV2'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'RE4'
,'RETENCION 4%'
,'RE4'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'RETENCION 4%', NOM_COR_IMPTO = 'RE4', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'RE4'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'RIS'
,'RETENCION IVA SUBCONTRATACION'
,'RIS6'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'RETENCION IVA SUBCONTRATACION', NOM_COR_IMPTO = 'RIS6', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', 
 FEC_ACTU = SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'RIS'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'REI'
,'RETENCION 2/3 IVA'
,'R2/3'
,NULL
,'R'
,'I'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'RETENCION 2/3 IVA', NOM_COR_IMPTO = 'R2/3', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'I', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'REI'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'REZ'
,'RETENCION 2/3 IVA'
,'R2/3 ZF'
,NULL
,'R'
,'I'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'RETENCION 2/3 IVA', NOM_COR_IMPTO = 'R2/3 ZF', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'I', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'N', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'REZ'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'CSG'
,'CEDULAR SERVICIOS GRAVADOS'
,'CSG'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'CEDULAR SERVICIOS GRAVADOS', NOM_COR_IMPTO = 'CSG', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'S', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'CSG'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'CSE'
,'CEDULAR SERVICIOS EXENTOS'
,'CSE'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'CEDULAR SERVICIOS EXENTOS', NOM_COR_IMPTO = 'CSE', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'S', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'CSE'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'CAE'
,'CEDULAR ACTIVIDAD EMPRESARIAL'
,'CAE'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'CEDULAR ACTIVIDAD EMPRESARIAL', NOM_COR_IMPTO = 'CAE', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU 
 = SYSDATE, MCA_CALCULA_PROV = 'S', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'CAE'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'CME'
,'CEDULAR MÉDICOS'
,'CME'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'CEDULAR MÉDICOS', NOM_COR_IMPTO = 'CME', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, 
 MCA_CALCULA_PROV = 'S', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'CME'
;
END;
BEGIN 
INSERT INTO TRON2000.A1001100
(COD_IMPTO
,NOM_IMPTO
,NOM_COR_IMPTO
,TIP_IVA
,TIP_IMPTO
,TIP_BASE_IMPTO
,TIP_CALCULO
,NOM_PRG_IMPTO
,COD_USR
,FEC_ACTU
,MCA_CALCULA_PROV
,TIP_EXCLUSION
)
VALUES ( 
'CGF'
,'CEDULAR SERV GRAVADOS FORAN'
,'CGF'
,NULL
,'R'
,'B'
,NULL
,NULL
,'TRON2000'
,SYSDATE
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A1001100
 SET  NOM_IMPTO = 'CEDULAR SERV GRAVADOS FORAN', NOM_COR_IMPTO = 'CGF', TIP_IVA = NULL, TIP_IMPTO = 'R', TIP_BASE_IMPTO = 'B', TIP_CALCULO = NULL, NOM_PRG_IMPTO = NULL, COD_USR = 'TRON2000', FEC_ACTU = 
 SYSDATE, MCA_CALCULA_PROV = 'S', TIP_EXCLUSION = NULL
 WHERE  COD_IMPTO = 'CGF'
;
END;
END;
/
COMMIT;