BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4000'
,'CAPTURAR NUEVO SINIESTRO'
,'CAPNVOSIN'
,'CAPTURAR NUEVO SINIESTRO'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'CAPTURAR NUEVO SINIESTRO', NOM_COR_TRAMITE = 'CAPNVOSIN', OBS_HISTORICO = 'CAPTURAR NUEVO SINIESTRO', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4000'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4001'
,'APERTURAR EXPEDIENTE ADICIONA'
,'APEREXP'
,'APERTURAR EXPEDIENTE ADICIONAL NVO INTERVINIENTE'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'APERTURAR EXPEDIENTE ADICIONA', NOM_COR_TRAMITE = 'APEREXP', OBS_HISTORICO = 'APERTURAR EXPEDIENTE ADICIONAL NVO INTERVINIENTE', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4001'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4002'
,'REAPERTURAR EXPEDIENTE'
,'REAEXP'
,'REAPERTURAR EXPEDIENTE'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'S'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'REAPERTURAR EXPEDIENTE', NOM_COR_TRAMITE = 'REAEXP', OBS_HISTORICO = 'REAPERTURAR EXPEDIENTE', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'S', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4002'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4003'
,'REASIGNAR TRAMITADOR'
,'REATRAM'
,'REASIGNAR TRAMITADOR'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'REASIGNAR TRAMITADOR', NOM_COR_TRAMITE = 'REATRAM', OBS_HISTORICO = 'REASIGNAR TRAMITADOR', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4003'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4004'
,'REASIGNAR CENTRO TRAMITADOR'
,'REACENTRA'
,'REASIGNAR CENTRO TRAMITADOR'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'REASIGNAR CENTRO TRAMITADOR', NOM_COR_TRAMITE = 'REACENTRA', OBS_HISTORICO = 'REASIGNAR CENTRO TRAMITADOR', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4004'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4005'
,'ANALISIS Y ACTUALIZACION EXP'
,'ACTEXP'
,'ANALISIS Y ACTUALIZACION DEL EXPEDIENTE AGENDA'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ANALISIS Y ACTUALIZACION EXP', NOM_COR_TRAMITE = 'ACTEXP', OBS_HISTORICO = 'ANALISIS Y ACTUALIZACION DEL EXPEDIENTE AGENDA', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4005'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4006'
,'SOLICITAR INF Y DOCUMENTACION'
,'SOLICINFO'
,'SOLICITAR INFORMACION / DOCUMENTACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'SOLICITAR INF Y DOCUMENTACION', NOM_COR_TRAMITE = 'SOLICINFO', OBS_HISTORICO = 'SOLICITAR INFORMACION / DOCUMENTACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4006'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4007'
,'RECEPCIONAR INFORMACI0N Y DOC'
,'RECEPINFO'
,'RECEPCIONAR INFORMACION / DOCUMENTACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,15
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'RECEPCIONAR INFORMACI0N Y DOC', NOM_COR_TRAMITE = 'RECEPINFO', OBS_HISTORICO = 'RECEPCIONAR INFORMACION / DOCUMENTACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 15, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4007'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4008'
,'GESTIONAR CONTACTOS'
,'GESTCONT'
,'GESTIONAR CONTACTOS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,10
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'GESTIONAR CONTACTOS', NOM_COR_TRAMITE = 'GESTCONT', OBS_HISTORICO = 'GESTIONAR CONTACTOS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 10, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4008'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4009'
,'INTERVENCION DE PROFESIONALES'
,'INTERPROF'
,'INTERVENCION DE PROFESIONALES'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,3
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'INTERVENCION DE PROFESIONALES', NOM_COR_TRAMITE = 'INTERPROF', OBS_HISTORICO = 'INTERVENCION DE PROFESIONALES', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = 
 NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 
 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 3, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4009'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4010'
,'COMUNICAR OFERTA FORMAL'
,'OFERTAFOR'
,'COMUNICAR OFERTA FORMAL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,3
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'COMUNICAR OFERTA FORMAL', NOM_COR_TRAMITE = 'OFERTAFOR', OBS_HISTORICO = 'COMUNICAR OFERTA FORMAL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 3, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4010'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4011'
,'VIABILIDAD JUDICIAL MEDIACION'
,'VIABILIDA'
,'VIABILIDAD JUDICIAL / MEDIACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,3
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'VIABILIDAD JUDICIAL MEDIACION', NOM_COR_TRAMITE = 'VIABILIDA', OBS_HISTORICO = 'VIABILIDAD JUDICIAL / MEDIACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = 
 NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 
 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 3, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4011'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4012'
,'COMUNICAR REHUSE RECHAZO PRES'
,'COMUNRECH'
,'COMUNICAR REHUSE / RECHAZO DE PRESTACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'COMUNICAR REHUSE RECHAZO PRES', NOM_COR_TRAMITE = 'COMUNRECH', OBS_HISTORICO = 'COMUNICAR REHUSE / RECHAZO DE PRESTACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4012'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4013'
,'RECLAMAR DAÑOS / RECOBRO'
,'RECDANIO'
,'RECLAMAR DAÑOS / RECOBRO'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,10
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'RECLAMAR DAÑOS / RECOBRO', NOM_COR_TRAMITE = 'RECDANIO', OBS_HISTORICO = 'RECLAMAR DAÑOS / RECOBRO', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 10, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4013'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4014'
,'REPETICION'
,'REPETICIO'
,'REPETICION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,5
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'REPETICION', NOM_COR_TRAMITE = 'REPETICIO', OBS_HISTORICO = 'REPETICION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, 
 MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', 
 NUM_DIAS_CONTROL = 5, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4014'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4015'
,'RESPONSABILIDAD CIVIL'
,'RESPCIVIL'
,'RESPONSABILIDAD CIVIL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,60
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'RESPONSABILIDAD CIVIL', NOM_COR_TRAMITE = 'RESPCIVIL', OBS_HISTORICO = 'RESPONSABILIDAD CIVIL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 60, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4015'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4016'
,'ATENCION DEL LESIONADO'
,'ATTENLES'
,'ATENCION DEL LESIONADO'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,15
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ATENCION DEL LESIONADO', NOM_COR_TRAMITE = 'ATTENLES', OBS_HISTORICO = 'ATENCION DEL LESIONADO', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 15, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4016'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4017'
,'SEGUIMIENTO MEDICO LESIONADO'
,'MEDLES'
,'SEGUIMIENTO MEDICO LESIONADO'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,15
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'SEGUIMIENTO MEDICO LESIONADO', NOM_COR_TRAMITE = 'MEDLES', OBS_HISTORICO = 'SEGUIMIENTO MEDICO LESIONADO', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 15, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4017'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4018'
,'ATENCION FAMILIARES FALLECIDO'
,'ATENFAMIL'
,'ATENCION FAMILIARES FALLECIDO'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ATENCION FAMILIARES FALLECIDO', NOM_COR_TRAMITE = 'ATENFAMIL', OBS_HISTORICO = 'ATENCION FAMILIARES FALLECIDO', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = 
 NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 
 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4018'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4019'
,'RECUPERACION Y VALORACION RES'
,'RECVALRES'
,'RECUPERACION Y VALORACION DE RESTOS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,15
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'RECUPERACION Y VALORACION RES', NOM_COR_TRAMITE = 'RECVALRES', OBS_HISTORICO = 'RECUPERACION Y VALORACION DE RESTOS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 15, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4019'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4020'
,'LIQUIDACION DE RESTOS'
,'LIQREST'
,'LIQUIDACION DE RESTOS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,3
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'LIQUIDACION DE RESTOS', NOM_COR_TRAMITE = 'LIQREST', OBS_HISTORICO = 'LIQUIDACION DE RESTOS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 3, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4020'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4021'
,'LOCALIZACION DE VEHICULO'
,'LOCVEHIC'
,'LOCALIZACION DE VEHICULO'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,180
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'LOCALIZACION DE VEHICULO', NOM_COR_TRAMITE = 'LOCVEHIC', OBS_HISTORICO = 'LOCALIZACION DE VEHICULO', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 180, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4021'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4022'
,'DESAPARICION / PERDIDA TOTAL'
,'PT'
,'DESAPARICION / PERDIDA TOTAL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'DESAPARICION / PERDIDA TOTAL', NOM_COR_TRAMITE = 'PT', OBS_HISTORICO = 'DESAPARICION / PERDIDA TOTAL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4022'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4023'
,'COMUNICACION CORRESPONSAL'
,'COMUNCORR'
,'COMUNICACION CORRESPONSAL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'COMUNICACION CORRESPONSAL', NOM_COR_TRAMITE = 'COMUNCORR', OBS_HISTORICO = 'COMUNICACION CORRESPONSAL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4023'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4024'
,'INICIAR PROCESO JUDICIAL'
,'INIPROCJU'
,'INICIAR PROCESO JUDICIAL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,5
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'INICIAR PROCESO JUDICIAL', NOM_COR_TRAMITE = 'INIPROCJU', OBS_HISTORICO = 'INICIAR PROCESO JUDICIAL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 5, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4024'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4025'
,'GESTIONAR PROCESO JUDICIAL'
,'GESTPROCJ'
,'GESTIONAR PROCESO JUDICIAL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,15
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'GESTIONAR PROCESO JUDICIAL', NOM_COR_TRAMITE = 'GESTPROCJ', OBS_HISTORICO = 'GESTIONAR PROCESO JUDICIAL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 15, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4025'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4026'
,'GESTIONAR RECURSO / APELACION'
,'GESRECAPE'
,'GESTIONAR RECURSO / APELACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,15
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'GESTIONAR RECURSO / APELACION', NOM_COR_TRAMITE = 'GESRECAPE', OBS_HISTORICO = 'GESTIONAR RECURSO / APELACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = 
 NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 
 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 15, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4026'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4027'
,'EJECUTAR SENTENCIA'
,'EJESENTEN'
,'EJECUTAR SENTENCIA'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'EJECUTAR SENTENCIA', NOM_COR_TRAMITE = 'EJESENTEN', OBS_HISTORICO = 'EJECUTAR SENTENCIA', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4027'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4028'
,'AJUSTAR RESERVAS'
,'AJUSRES'
,'AJUSTAR RESERVAS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'AJUSTAR RESERVAS', NOM_COR_TRAMITE = 'AJUSRES', OBS_HISTORICO = 'AJUSTAR RESERVAS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = 
 NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 
 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4028'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4029'
,'REALIZAR PAGOS'
,'LIQUID'
,'REALIZAR PAGOS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'REALIZAR PAGOS', NOM_COR_TRAMITE = 'LIQUID', OBS_HISTORICO = 'REALIZAR PAGOS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, 
 MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', 
 NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4029'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4030'
,'REALIZAR COBROS'
,'COBROS'
,'REALIZAR COBROS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'REALIZAR COBROS', NOM_COR_TRAMITE = 'COBROS', OBS_HISTORICO = 'REALIZAR COBROS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = 
 NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 
 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4030'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4031'
,'ANULAR PAGOS / COBROS'
,'ANULIQ'
,'ANULAR PAGOS / COBROS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ANULAR PAGOS / COBROS', NOM_COR_TRAMITE = 'ANULIQ', OBS_HISTORICO = 'ANULAR PAGOS / COBROS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4031'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4032'
,'TRASPASOS ECONOMICOS'
,'TRASPECO'
,'TRASPASOS ECONOMICOS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'TRASPASOS ECONOMICOS', NOM_COR_TRAMITE = 'TRASPECO', OBS_HISTORICO = 'TRASPASOS ECONOMICOS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4032'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4033'
,'CONSIGNACION JUDICIAL'
,'CONSJUD'
,'CONSIGNACION JUDICIAL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'CONSIGNACION JUDICIAL', NOM_COR_TRAMITE = 'CONSJUD', OBS_HISTORICO = 'CONSIGNACION JUDICIAL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4033'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4034'
,'RECUPERACION PAGOS INDEBIDOS'
,'RECLIQ'
,'RECUPERACION PAGOS INDEBIDOS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,15
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'RECUPERACION PAGOS INDEBIDOS', NOM_COR_TRAMITE = 'RECLIQ', OBS_HISTORICO = 'RECUPERACION PAGOS INDEBIDOS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 15, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4034'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4035'
,'RECUPERAR CONSIGNACION JUDICI'
,'RECCONSJ'
,'RECUPERAR CONSIGNACION JUDICIAL'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'RECUPERAR CONSIGNACION JUDICI', NOM_COR_TRAMITE = 'RECCONSJ', OBS_HISTORICO = 'RECUPERAR CONSIGNACION JUDICIAL', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = 
 NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 
 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4035'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4036'
,'CALIFICAR EXPEDIENTE'
,'CALEXP'
,'CALIFICAR EXPEDIENTE'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'CALIFICAR EXPEDIENTE', NOM_COR_TRAMITE = 'CALEXP', OBS_HISTORICO = 'CALIFICAR EXPEDIENTE', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4036'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4037'
,'ACCIONES PREVENTIVAS'
,'ACCPREV'
,'ACCIONES PREVENTIVAS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,10
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ACCIONES PREVENTIVAS', NOM_COR_TRAMITE = 'ACCPREV', OBS_HISTORICO = 'ACCIONES PREVENTIVAS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 10, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4037'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4038'
,'ACCIONES DE INVESTIGACION'
,'ACCINV'
,'ACCIONES DE INVESTIGACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,5
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ACCIONES DE INVESTIGACION', NOM_COR_TRAMITE = 'ACCINV', OBS_HISTORICO = 'ACCIONES DE INVESTIGACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 5, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4038'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4039'
,'CONFIRMAR FRAUDE'
,'CONFRAUDE'
,'CONFIRMAR FRAUDE'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,5
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'CONFIRMAR FRAUDE', NOM_COR_TRAMITE = 'CONFRAUDE', OBS_HISTORICO = 'CONFIRMAR FRAUDE', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = 
 NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 
 'S', NUM_DIAS_CONTROL = 5, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4039'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4040'
,'RECEPCION Y ANALISIS DE QUEJA'
,'RECEPQUEJ'
,'RECEPCION Y ANALISIS DE QUEJA / RECLAMACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'RECEPCION Y ANALISIS DE QUEJA', NOM_COR_TRAMITE = 'RECEPQUEJ', OBS_HISTORICO = 'RECEPCION Y ANALISIS DE QUEJA / RECLAMACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4040'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4041'
,'ACCIONES ACLARATORIAS'
,'ACCACLA'
,'ACCIONES ACLARATORIAS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,5
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ACCIONES ACLARATORIAS', NOM_COR_TRAMITE = 'ACCACLA', OBS_HISTORICO = 'ACCIONES ACLARATORIAS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, 
 COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'N', 
 MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 5, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4041'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4042'
,'COMUNICAR RESOLUCION DE QUEJA'
,'COMRESOL'
,'COMUNICAR RESOLUCION DE QUEJA / RECLAMACION'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,1
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'COMUNICAR RESOLUCION DE QUEJA', NOM_COR_TRAMITE = 'COMRESOL', OBS_HISTORICO = 'COMUNICAR RESOLUCION DE QUEJA / RECLAMACION', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, 
 COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT 
 = NULL, MCA_EXP_TERM = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 1, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4042'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4043'
,'IDENTIFICAR MOTIVO DE CIERRE'
,'IDENTCIER'
,'IDENTIFICAR MOTIVO DE CIERRE'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'IDENTIFICAR MOTIVO DE CIERRE', NOM_COR_TRAMITE = 'IDENTCIER', OBS_HISTORICO = 'IDENTIFICAR MOTIVO DE CIERRE', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = 
 NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 
 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4043'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4044'
,'ANALIZAR CUMPLIMIENTO COMPROM'
,'CUMCOMP'
,'ANALIZAR CUMPLIMIENTO DE COMPROMISOS'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'N'
,'S'
,10
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'ANALIZAR CUMPLIMIENTO COMPROM', NOM_COR_TRAMITE = 'CUMCOMP', OBS_HISTORICO = 'ANALIZAR CUMPLIMIENTO DE COMPROMISOS', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO 
 = NULL, COD_TRAMITE_NEGATIVO = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM 
 = 'N', MCA_INSERTA_MANUAL = 'S', NUM_DIAS_CONTROL = 10, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4044'
;
END;
BEGIN 
INSERT INTO TRON2000.G7500020
(COD_CIA
,COD_TRAMITE
,NOM_TRAMITE
,NOM_COR_TRAMITE
,OBS_HISTORICO
,NUM_DIAS_AGENDA
,OBS_AGENDA
,COD_TRAMITE_POSITIVO
,COD_TRAMITE_NEGATIVO
,MCA_INH
,COD_USR
,FEC_ACTU
,NOM_PRG_PREVIO
,NOM_PRG_POSTERIOR
,MCA_TERM_AUT
,NOM_PRG_TERM_AUT
,MCA_EXP_TERM
,MCA_INSERTA_MANUAL
,NUM_DIAS_CONTROL
,MCA_MOD_FEC_CONTROL
,MCA_MOD_CUALQ_TRAMITADOR
)
VALUES ( 
1
,'4045'
,'CERRAR EXPEDIENTE'
,'CERRAREXP'
,'CERRAR EXPEDIENTE'
,NULL
,NULL
,NULL
,NULL
,'N'
,'TRON2000'
,SYSDATE
,NULL
,NULL
,'N'
,NULL
,'S'
,'S'
,0
,'S'
,'S'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.G7500020
 SET  NOM_TRAMITE = 'CERRAR EXPEDIENTE', NOM_COR_TRAMITE = 'CERRAREXP', OBS_HISTORICO = 'CERRAR EXPEDIENTE', NUM_DIAS_AGENDA = NULL, OBS_AGENDA = NULL, COD_TRAMITE_POSITIVO = NULL, COD_TRAMITE_NEGATIVO 
 = NULL, MCA_INH = 'N', COD_USR = 'TRON2000', FEC_ACTU = SYSDATE, NOM_PRG_PREVIO = NULL, NOM_PRG_POSTERIOR = NULL, MCA_TERM_AUT = 'N', NOM_PRG_TERM_AUT = NULL, MCA_EXP_TERM = 'S', MCA_INSERTA_MANUAL = 
 'S', NUM_DIAS_CONTROL = 0, MCA_MOD_FEC_CONTROL = 'S', MCA_MOD_CUALQ_TRAMITADOR = 'S'
 WHERE  COD_CIA = 1 AND  COD_TRAMITE = '4045'
;
END;
END;
/
COMMIT;