BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Dn'
,'CV'
,'AM'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'CV', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Dn'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DN'
,'PV'
,'AM'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DN'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'H03'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'H03'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'H05'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'H05'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'H06'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'H06'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'H09'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'H09'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'H10'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'H10'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'H11'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'H11'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'ANT'
,'CA'
,'CO'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'CA', COD_AGRUP_IMPTO = 'CO', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'ANT'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y16'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y16'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y17'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y17'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y26'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y26'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DN1'
,'PV'
,'AM'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DN1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CA6'
,'MP'
,'AM'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'S'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'S', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CA6'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'AF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'AF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'AM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'AM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BF2'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BF2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BF3'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BF3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BF4'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BF4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BM2'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BM3'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BM3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'BM4'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'BM4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CF2'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CF2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CF3'
,'PC'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CF3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CF4'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CF4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CF5'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CF5'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CM2'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CM3'
,'PC'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CM3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CM4'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CM4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CM5'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CM5'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DF1'
,'DC'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'DC', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DF2'
,'DC'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'DC', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DF2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DF3'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DF3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DM1'
,'DC'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'DC', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DM2'
,'DC'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'DC', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'DM3'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'DM3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'FF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'FF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'FM2'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'FM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'HF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'HF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'HM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'HM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'I03'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'I03'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'I04'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'I04'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IF2'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IF2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'I05'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'I05'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IF3'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IF3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'I07'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'I07'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IF4'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IF4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'I08'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'I08'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IF5'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IF5'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'ID2'
,'PS'
,NULL
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = NULL, TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'ID2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IF6'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IF6'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IM2'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IM3'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IM3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IM4'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IM4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IM5'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IM5'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IM6'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IM6'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IR2'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IR2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'LF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'LF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IR3'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IR3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'LM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'LM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IR4'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IR4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'NF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'NF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'IS2'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'IS2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'NM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'NM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'OF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'OF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'OM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'OM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'PF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'PF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'PM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'PM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'RM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'RM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'RM2'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'RM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'RM3'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'RM3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'RM4'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'RM4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'RM5'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'RM5'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'SF1'
,'PC'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'SF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'SF2'
,'PC'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'SF2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'SM1'
,'PC'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'SM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'SM2'
,'PC'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'SM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'TF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'TF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'TF2'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'TF2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'TM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'TM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'TM2'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'TM2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'UF1'
,'MP'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'UF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'UM1'
,'MP'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'MP', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'UM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'VF1'
,'PC'
,'AF'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'VF1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'VM1'
,'PC'
,'AM'
,'AC'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PC', COD_AGRUP_IMPTO = 'AM', TIP_CTO = 'AC', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'VM1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y04'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y04'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y08'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y08'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y10'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y10'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y11'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y11'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y12'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y12'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y13'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y13'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'Y14'
,'PS'
,'IS'
,'SI'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PS', COD_AGRUP_IMPTO = 'IS', TIP_CTO = 'SI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'Y14'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'ac'
,'PV'
,'AF'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,NULL
,NULL
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'AF', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = NULL, MCA_ORD_COMPRA = NULL, 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'ac'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'AP1'
,'PV'
,'CO'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'CO', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'AP1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'AP2'
,'PV'
,'CO'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'CO', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'AP2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'CAM'
,'PV'
,'CO'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'CO', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'CAM'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'APC'
,'PV'
,'CO'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'CO', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'APC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021101
(COD_CTO_COB_PAG
,COD_AGRUP_CTABLE
,COD_AGRUP_IMPTO
,TIP_CTO
,FEC_ACTU
,COD_USR
,COD_PPTO
,NUM_DIAS_PAGO
,MCA_ANTICIPO
,MCA_ORD_COMPRA
,TIP_TRATA_CTO
)
VALUES ( 
'AP3'
,'PV'
,'CO'
,'CP'
,SYSDATE
,'TRON2000'
,NULL
,NULL
,'N'
,'N'
,NULL
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021101
 SET  COD_AGRUP_CTABLE = 'PV', COD_AGRUP_IMPTO = 'CO', TIP_CTO = 'CP', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000', COD_PPTO = NULL, NUM_DIAS_PAGO = NULL, MCA_ANTICIPO = 'N', MCA_ORD_COMPRA = 'N', 
 TIP_TRATA_CTO = NULL
 WHERE  COD_CTO_COB_PAG = 'AP3'
;
END;
END;
/
COMMIT;