BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'IS'
,'IMPTO DE SINIESTROS'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'IMPTO DE SINIESTROS', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'IS'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'EM'
,'EMISIÓN'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'EMISIÓN', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'EM'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CO'
,'COBRANZA'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'COBRANZA', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'CO'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'SA'
,'SALVAMENTOS'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'SALVAMENTOS', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'SA'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'DE'
,'DEDUCIBLES'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'DEDUCIBLES', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'DE'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'OT'
,'OTROS'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'OTROS', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'OT'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'DV'
,'DEVOLUCIONES'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'DEVOLUCIONES', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'DV'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'AF'
,'AGENTES FÍSICAS'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'AGENTES FÍSICAS', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'AF'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'AM'
,'AGENTES MORAL'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'AGENTES MORAL', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'AM'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'SF'
,'HON SIN FÍSICAS'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'HON SIN FÍSICAS', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'SF'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'SM'
,'HON SIN MORALES'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'HON SIN MORALES', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'SM'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'SN'
,'HON MEDICOS'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'HON MEDICOS', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'SN'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'GF'
,'GRUEROS FÍSICAS'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'GRUEROS FÍSICAS', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'GF'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'GM'
,'GRUEROS MORALES'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'GRUEROS MORALES', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'GM'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'SC'
,'CMPA SALV CARO'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'CMPA SALV CARO', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'SC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'VR'
,'VENCIM Y RESCATES'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'VENCIM Y RESCATES', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'VR'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'V1'
,'VIDA 93-XXI'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'VIDA 93-XXI', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'V1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'V2'
,'VIDA 133/135'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'VIDA 133/135', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'V2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'V3'
,'VIDA 142'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'VIDA 142', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'V3'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'V4'
,'VIDA 156'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'VIDA 156', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'V4'
;
END;
BEGIN 
INSERT INTO TRON2000.A5021103
(COD_AGRUP_IMPTO
,NOM_AGRUP_IMPTO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'V5'
,'VIDA 185'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5021103
 SET  NOM_AGRUP_IMPTO = 'VIDA 185', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  COD_AGRUP_IMPTO = 'V5'
;
END;
END;
/
COMMIT;