BEGIN
NULL;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CI'
,'CUENTA INTERCOMPAÑIAS'
,'N'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CUENTA INTERCOMPAÑIAS', MCA_GESTION = 'N', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CI'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'IM'
,'DESCUENTO IMPUESTOS'
,'S'
,'N'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DESCUENTO IMPUESTOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'N', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'IM'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'RC'
,'DESCUENTO RECARGOS'
,'S'
,'N'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DESCUENTO RECARGOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'N', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'RC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'GS'
,'GESTION.  CUENTA DE GESTION'
,'S'
,'N'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'GESTION.  CUENTA DE GESTION', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'N', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'GS'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'EF'
,'RECAUDACION EN EFECTIVO'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'RECAUDACION EN EFECTIVO', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'EF'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CH'
,'RECAUDACION EN CHEQUE'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'RECAUDACION EN CHEQUE', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CH'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'TA'
,'RECAUDACION TARJETA DE CREDITO'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'RECAUDACION TARJETA DE CREDITO', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'TA'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'BA'
,'BANCOS'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'BANCOS', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'BA'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'DP'
,'DIFERENCIA DE CAMBIO POSITIVA'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DIFERENCIA DE CAMBIO POSITIVA', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'DP'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'DN'
,'DIFERENCIA DE CAMBIO NEGATIVA'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DIFERENCIA DE CAMBIO NEGATIVA', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'DN'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CT'
,'COMISIONES TARJETA DE CREDITO'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COMISIONES TARJETA DE CREDITO', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CT'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'IR'
,'IMPUESTOS RETENCIONES'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'IMPUESTOS RETENCIONES', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'IR'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CF'
,'CHEQUES POSTFECHADOS'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CHEQUES POSTFECHADOS', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CF'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'FF'
,'FONDO FIJO'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'FONDO FIJO', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'FF'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CA'
,'COBROS ANTICIPADOS'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COBROS ANTICIPADOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CA'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CP'
,'CTAS X PAG PROVEED. TERCEROS'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CTAS X PAG PROVEED. TERCEROS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CP'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CC'
,'CUENTA CORRIENTE DEL AGENTE'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CUENTA CORRIENTE DEL AGENTE', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'NC'
,'NOTAS DE CREDITO ORDENES PAGO'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'NOTAS DE CREDITO ORDENES PAGO', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'NC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'TT'
,'CTA.PUENTE TRASPASOS TESORERIA'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CTA.PUENTE TRASPASOS TESORERIA', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'TT'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CN'
,'DIFER. COBRANZA MENOS'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DIFER. COBRANZA MENOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CN'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CM'
,'DIFER. COBRANZA MAS'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DIFER. COBRANZA MAS', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CM'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'RT'
,'RETENCION TARJETAS DE CREDITO'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'RETENCION TARJETAS DE CREDITO', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'RT'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CD'
,'RECUPERACION CHEQUES DEVUELTOS'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'RECUPERACION CHEQUES DEVUELTOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CD'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'SL'
,'CANCELACION SIN LIBRO IVA VTAS'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CANCELACION SIN LIBRO IVA VTAS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'SL'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'RA'
,'REASEGURO'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'REASEGURO', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'RA'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'IN'
,'INCIDENCIAS EN COBROS MASIVOS'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'INCIDENCIAS EN COBROS MASIVOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'IN'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'AN'
,'ANTICIPOS VARIOS (ORD. PAGO)PP'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'ANTICIPOS VARIOS (ORD. PAGO)PP', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'AN'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CS'
,'CHEQUES CADUCOS'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CHEQUES CADUCOS', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CS'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CQ'
,'CHEQUES CADUCOS A CTA INGRESO'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'CHEQUES CADUCOS A CTA INGRESO', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CQ'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'LC'
,'LIQUIDACION COMISIONES TRANSI.'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'LIQUIDACION COMISIONES TRANSI.', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'LC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'PA'
,'PRIMAS AVISADAS'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'PRIMAS AVISADAS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'PA'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'NS'
,'DESCUENTOS A PAGOS SINIESTROS'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DESCUENTOS A PAGOS SINIESTROS', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'NS'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'AS'
,'COASEGUROS CESIONARIA'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COASEGUROS CESIONARIA', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'AS'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'SC'
,'COASEGUROS CEDENTES'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COASEGUROS CEDENTES', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'SC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'DV'
,'DEVOLUCION ANTICIPOS'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DEVOLUCION ANTICIPOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'DV'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CO'
,'COASEGURO REMESA'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COASEGURO REMESA', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CO'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'RE'
,'REASEGURO REMESA'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'REASEGURO REMESA', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'RE'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'GR'
,'GASTO CHEQUE DEVUELTO BANCO'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'GASTO CHEQUE DEVUELTO BANCO', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'GR'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'DC'
,'DIFERENCIA DE CIERRE CAJA'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'DIFERENCIA DE CIERRE CAJA', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'DC'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'VP'
,'PAGOS ORDENES DE PAGO DE VIDA'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'PAGOS ORDENES DE PAGO DE VIDA', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'VP'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'AR'
,'ANUL. RETENCION CON REEXPED.'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'ANUL. RETENCION CON REEXPED.', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'AR'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'C1'
,'COASEGURO CEDIDO'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COASEGURO CEDIDO', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'C1'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'C2'
,'COASEGURO ACEPTADO'
,'S'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COASEGURO ACEPTADO', MCA_GESTION = 'S', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'C2'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'RP'
,'RESERVA DE PRIMAS'
,'N'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'RESERVA DE PRIMAS', MCA_GESTION = 'N', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'RP'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'EB'
,'EFECTIVO EN EL BANCO'
,'N'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'EFECTIVO EN EL BANCO', MCA_GESTION = 'N', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'EB'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'BP'
,'EFECTIVO BANCO PAIS'
,'N'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'EFECTIVO BANCO PAIS', MCA_GESTION = 'N', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'BP'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'BE'
,'EFECTIVO BANCO EXT.'
,'N'
,NULL
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'EFECTIVO BANCO EXT.', MCA_GESTION = 'N', MCA_PREDEFINIDO = NULL, FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'BE'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'FA'
,'FONDO DE INVERSION'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'FONDO DE INVERSION', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'FA'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CW'
,'COMPENSACION COBROS CME E-COMM'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COMPENSACION COBROS CME E-COMM', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CW'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'CR'
,'COMISION DE COBRO DE RECIBOS'
,'S'
,'N'
,SYSDATE
,'TRON2000'
);
COMMIT;
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'COMISION DE COBRO DE RECIBOS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'N', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'CR'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'OT'
,'OTROS'
,'S'
,'N'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'OTROS', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'N', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'OT'
;
END;
BEGIN 
INSERT INTO TRON2000.A5022602
(TIP_CTA_SIMP
,NOM_TIP_CTA_SIMP
,MCA_GESTION
,MCA_PREDEFINIDO
,FEC_ACTU
,COD_USR
)
VALUES ( 
'BT'
,'BANCO TRANSFERENCIA'
,'S'
,'S'
,SYSDATE
,'TRON2000'
);
EXCEPTION 
WHEN DUP_VAL_ON_INDEX THEN 
UPDATE TRON2000.A5022602
 SET  NOM_TIP_CTA_SIMP = 'BANCO TRANSFERENCIA', MCA_GESTION = 'S', MCA_PREDEFINIDO = 'S', FEC_ACTU = SYSDATE, COD_USR = 'TRON2000'
 WHERE  TIP_CTA_SIMP = 'BT'
;
END;
END;
/
COMMIT;