--------------------------------------------------------
-- Archivo creado  - jueves-diciembre-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TA999501
--------------------------------------------------------

  CREATE TABLE "TRP_MX_DL"."TA999501" 
   (	"COD_CIA" NUMBER(2,0), 
	"COD_SECTOR" NUMBER(4,0), 
	"COD_RAMO" NUMBER(3,0), 
	"NUM_POLIZA_GRUPO" VARCHAR2(13 BYTE), 
	"NUM_CONTRATO" NUMBER(5,0), 
	"NUM_SUBCONTRATO" NUMBER(5,0), 
	"COD_CANAL3" VARCHAR2(4 BYTE), 
	"COD_PRODUCTO" NUMBER(3,0), 
	"COD_AMB_CIRCULACION" NUMBER(3,0), 
	"COD_TIP_INDEM" NUMBER(3,0), 
	"COD_TIP_INDEM_RENOV" NUMBER(3,0), 
	"FEC_VALIDEZ" DATE, 
	"MCA_INH" VARCHAR2(1 BYTE), 
	"COD_USR" VARCHAR2(8 BYTE), 
	"FEC_ACTU" DATE
   ) ;

   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_CIA" IS 'COMPANIA';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_SECTOR" IS 'SECTOR';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_RAMO" IS 'RAMO';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."NUM_POLIZA_GRUPO" IS 'NUMERO DE POLIZA GRUPO';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."NUM_CONTRATO" IS 'NUMERO DE CONTRATO';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."NUM_SUBCONTRATO" IS 'NUMERO DE SUB CONTRATO';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_CANAL3" IS 'NIVEL 3 CANAL DE COMERCIALIZACION';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_PRODUCTO" IS 'CODIGO DE PRODUCTO';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_AMB_CIRCULACION" IS 'CODIGO DEL AMBITO DE CIRCULACION';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_TIP_INDEM" IS 'CODIGO DEL TIPO DE INDEMNIZACION';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_TIP_INDEM_RENOV" IS 'CODIGO DEL TIPO DE INDEMNIZACION DE RENOVACION';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."FEC_VALIDEZ" IS 'FECHA DE VALIDEZ';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."MCA_INH" IS 'MARCA DE CAMPO INHABILITADO';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."COD_USR" IS 'USUARIO QUE ACTUALIZO LA FILA';
   COMMENT ON COLUMN "TRP_MX_DL"."TA999501"."FEC_ACTU" IS 'FECHA DE ACTUALIZACIÓN DE LA FILA';
   COMMENT ON TABLE "TRP_MX_DL"."TA999501"  IS 'TIPOS DE INDEMNIZACION POR PRODUCTO';
--------------------------------------------------------
--  DDL for Index SYS_C00145653
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00145653" ON "TRP_MX_DL"."TA999501" ("COD_CIA", "COD_SECTOR", "COD_RAMO", "NUM_POLIZA_GRUPO", "NUM_CONTRATO", "NUM_SUBCONTRATO", "COD_CANAL3", "COD_PRODUCTO", "COD_AMB_CIRCULACION", "COD_TIP_INDEM", "FEC_VALIDEZ") TABLESPACE DATOS
  ;
--------------------------------------------------------
--  Constraints for Table TA999501
--------------------------------------------------------

  ALTER TABLE "TRP_MX_DL"."TA999501" MODIFY ("COD_TIP_INDEM_RENOV" NOT NULL ENABLE);
  ALTER TABLE "TRP_MX_DL"."TA999501" MODIFY ("MCA_INH" NOT NULL ENABLE);
  ALTER TABLE "TRP_MX_DL"."TA999501" MODIFY ("COD_USR" NOT NULL ENABLE);
  ALTER TABLE "TRP_MX_DL"."TA999501" MODIFY ("FEC_ACTU" NOT NULL ENABLE);
  ALTER TABLE "TRP_MX_DL"."TA999501" ADD PRIMARY KEY ("COD_CIA", "COD_SECTOR", "COD_RAMO", "NUM_POLIZA_GRUPO", "NUM_CONTRATO", "NUM_SUBCONTRATO", "COD_CANAL3", "COD_PRODUCTO", "COD_AMB_CIRCULACION", "COD_TIP_INDEM", "FEC_VALIDEZ")
  USING INDEX  ENABLE;
